service:
  name: todoList

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws

functions:
  addTodo:
    handler: src/functions/addTodo.handle
    events:
      - http:
          path: /todos/{id}
          method: POST
          cors: true
  findTodosByUser:
    handler: src/functions/findTodosByUser.handle
    events:
      - http:
          path: /todos/{id}
          method: GET
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH